services:
  - type: web
    name: instagram-downloader
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
